# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 514e2df34727432c6eeeb53405c55dd3ec691bd776eaf936ffdb74cd1c2bd64e991a5669d58f654da030da7b76756fb899860da8a49dfdf6d1224d0794a2043e

test:
  secret_key_base: 060e36c4a017b928da8382deb15df14a2e66ad629b72bd7466219db5011bdd4eec6227535dd74b29f9f28553ca06b55ebc831cc25f7395a24999a58e8ca9700f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
